### ISSUE TITLE
Server crash java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/PerViamInvenire#14]
Just added this mod, with MineColonies 1.0.8, but looks like the crash is not related minecolonies.

Minecraft Version: 1.16.5
PerviamInvenire:  1.16.5-0.0.37-ALPHA

Crash Log:
https://gist.github.com/EverettSummer/1b60533c34a1e2e5fe13b9404fac652d
Latest.log
https://gist.github.com/EverettSummer/58e747869b6c9c0c9a9eee325efa5640

**Comment by marchermans** [comment]
Fixed in the newest release.
