### ISSUE TITLE
Crash 1 18 2

### ISSUE THREAD

**Issue by XionioXMaster** [ldtteam/PerViamInvenire#17]
https://pastebin.com/muzaWU5k

**Comment by luffykick** [comment]
I just came to report this also.

**Comment by XionioXMaster** [comment]
> I just came to report this also. here is my similar crash report... bad spider. https://pastebin.com/9mHU3QLg

Spider-Man, Spider-Man.

**Comment by 5050Shauna** [comment]
I have a similar report!

https://pastebin.com/4DBEdqNg

**Comment by Reshy** [comment]
https://pastebin.com/bFE7SYQ4

Seems to occur when the spider attempts to climb something.

**Comment by marchermans** [comment]
Fixed in the latest 1.19.x releases.
Sadly I won't be backporting this.
