### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by zyxkad** [ldtteam/PerViamInvenire#18]
Crash report:
[crash-2022-12-04_15.55.26-server.txt](https://github.com/ldtteam/PerViamInvenire/files/10149681/crash-2022-12-04_15.55.26-server.txt)
Crash on signle's game, if it's a client join a server, it will be fine.
Randomly crash, probably crash if there any monster?
Rejoin world and it won't crash immediately, but it will crash again if there are some mobs spawn.

**Comment by marchermans** [comment]
Fixed in the latest 1.19.x releases.
Sadly I won't be backporting this.
