### ISSUE TITLE
[1.18.2] Hard Crash:  Description: Ticking entity   java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by Reshy** [ldtteam/PerViamInvenire#20]
Crash Log: https://pastebin.com/L3uu5xHp

Annotated Debug Log:  https://pastebin.com/bKA4EHD7

-- Entity being ticked --
Details:
	Entity Type: minecraft:glow_squid (net.minecraft.world.entity.GlowSquid)
	Entity ID: 7891
	Entity Name: Glow Squid
	Entity's Exact location: 107.97, 24.00, 69.60
	Entity's Block location: World: (107,24,69), Section: (at 11,8,5 in 6,1,4; chunk contains blocks 96,-64,64 to 111,319,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

**Comment by marchermans** [comment]
Fixed in the latest 1.19.x releases.
Sadly I won't be backporting this.
