### ISSUE TITLE
Crash with villager pathing 

### ISSUE THREAD

**Issue by Darkere** [ldtteam/PerViamInvenire#23]
https://gist.github.com/IllegalCharacter/ca046b0ef91d857d38bbd395c0f194c0

They aparently have a couple villagers in Create Seats and think it could be related. 

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/418

 per_viam_invenire-1.19.2-0.1.58

**Comment by marchermans** [comment]
Closed by the same fix as for #22 
Should be fixed with 0.60-ALPHA
