### ISSUE TITLE
game crash ai or pathfinding

### ISSUE THREAD

**Issue by witdy002** [ldtteam/PerViamInvenire#4]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.64-ALPHA

### Logs

- latest.log: https://gist.github.com/witdy002/8cfb9883390c050befd7d89f981c2257

## Steps to reproduce the issue / details
Error occurs on save load, or just after.

### Notes
I am coming back to colony with a villager in my boat.
Running official minecolonies pack v1.8, updated to MineColonies Version: 0.14.64-ALPHA try fix the issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by witdy002** [comment]
removed PerViamInvenire mod, loaded fine, game was slower, played for couple hours, re-added PerViamInvenire, and it's working fine, so whatever pathing problem that was causing error was no longer present.

**Comment by marchermans** [comment]
It is probably something that is conditional to the villager in the boat.

I will make a fix in the near future. Sorry for the inconvenience

**Comment by Scarfo76** [comment]
Hello, I am havingt he same issue it appears, Sorry if i double posted. If i remove the Mod > Load the Server>  Shutdown > Load the mod back > start server, You are saying it may resolve it?

**Comment by marchermans** [comment]
Fixed in the new version
