### ISSUE TITLE
Minecolonies crashing Exit:0

### ISSUE THREAD

**Issue by Iknutar928** [ldtteam/PerViamInvenire#5]
[latest.log](https://github.com/ldtteam/PerViamInvenire/files/6251486/latest.log)

**Comment by bloodprince5** [comment]
https://gist.github.com/bloodprince5/39fa5c947465d65e90d7d005a5b7418c#file-latest-log

**Comment by bloodprince5** [comment]
[latest.log](https://github.com/ldtteam/PerViamInvenire/files/6361232/latest.log)

**Comment by marchermans** [comment]
Fixed in the new version.
