### ISSUE TITLE
NPE with the fox stroll goal

### ISSUE THREAD

**Issue by Thelonedevil** [ldtteam/PerViamInvenire#6]
Using the MineColonies Official pack version v1.9 with PVI version 1.16.5-0.0.21-ALPHA, I get an NPE as a fox moves through a village at night.  This has happens every time I load that world again, it gets to night and then crashes to desktop.

The issue seems to be at [this line](https://github.com/ldtteam/PerViamInvenire/blob/4a1dbdd977c11225cefc6bb27f2f44fa8fd025f0/src/main/java/com/ldtteam/perviaminvenire/pathfinding/PerViamInvenireGroundPathNavigator.java#L766) where it has checked it has a pathresult, but the pathresult.getPath() is returning null.

[Latest Log](https://paste.cosiestdevil.uk/paste?id=DB7F_TDo402W1N9u2v9LJQ==)
[Crash report](https://paste.cosiestdevil.uk/paste?id=PYRltw1IuUSsZMrYw306mA==)

**Comment by Scarfo76** [comment]
I have noticed a Line of Code regarding a fox on a Very Similar crash. This must be the same issue. Bump :)

**Comment by KrAzYGEEK32** [comment]
anyway to disable this mod for foxes specifically? having the same issue. crashes everytime 
[crash-2021-05-23_23.19.39-server.txt](https://github.com/ldtteam/PerViamInvenire/files/6528620/crash-2021-05-23_23.19.39-server.txt)

**Comment by marchermans** [comment]
Fixed in the new version
