### ISSUE TITLE
Server Crash With MineColonies v1.9

### ISSUE THREAD

**Issue by Scarfo76** [ldtteam/PerViamInvenire#7]
Minecraft Version:1.16.5
MineColonies Version: minecolonies-0.14.70-ALPHA-universal
Structurize Version: structurize-0.13.148-ALPHA-universal
Related Mods and their Versions:
All mods available in the v1.9 Download for Client and Server, On my latest tests, i have disabled Horseandstill, as well as Better caves and byg
Client side i have disabled Both Durability mods and Neat.

Expected behavior
Expect the server not to crash? idk :p

Actual behavior
Server randomly crashes with "server closed"
The server seems to randomly Crash, Random intervals. i have been mining in a cave, Feeding my pigs, or providing supplies to builders, and have seen it crash.

![image](https://user-images.githubusercontent.com/82480081/114636760-a7cc6480-9c7c-11eb-8c4a-a577e88888c6.png)

Steps to reproduce the issue
Place down camp / town hall, builder hut,
Provide some materials to builder and go explore
random crash, Server comes up fine, buy may crash again.
Logs
<script src="https://gist.github.com/Scarfo76/f058828bfa70817d5a16e8baef9d420c.js"></script> - latest.log:
crashlog:

Notes
Sorry if this is in the wrong section, I went to Cursefurge, MineColonies Official modpack And Selected Issue and Was brought here, If this is still the wrong location for this mod pack, to be supported. Are you able to provide me with that Link? i am sorry :/

**Comment by marchermans** [comment]
It should be fixed now.... But I am not 100% sure.
Test the new version.
