### ISSUE TITLE
NPE during illager raid

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/PerViamInvenire#9]
Minecraft Version: 1.16.5
MineColonies Version: minecolonies-0.14.131-ALPHA-universal.jar
PerViamInvenire Version: per-viam-invenire-1.16.5-0.0.21-ALPHA-universal.jar
Minecolonies Official Modpack Version (From curseforge): 1.16.5 v2.3

Expected behavior:
Pillager raid to go as normal

Actual behavior:
Game crash
[Logs](https://gist.github.com/Obbay2/f673ecd3c2e4108c9e2d849576788421)

Steps to reproduce:
1. Have several villagers in town when raid is starting
2. Wait for eventual crash
3. Profit?

**Comment by marchermans** [comment]
Fixed in the new release.
